# For a quick mongo/elasticSearch local enviornment

version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/volumes/mongo/data:/data/db
  elasticsearch:
    image: "elasticsearch:7.5.0"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./docker/volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=workflow.elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx2048m"
  kibana:
    image: "kibana:7.5.0"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
