openapi: 3.0.0
info:
  title: Clinical Donor Aggregator
  version: 1.0.0
security:
paths:
  /status:
    get:
      tags:
        - Health
      responses:
        "500":
          description: "app is not fully healthy"
        "200":
          description: "all components reporting healthy status"
          content:
            application/json:
              schema:
                type: object
  /index/program/{program_id}:
    post:
      tags:
        - Index Program
      description: index clinical and RDPC donors of a program
      parameters:
        - name: "program_id"
          in: "path"
          description: shortname of a program
          required: true
          type: "string"
      responses:
        "200":
          description: Successfully indexed a program
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Program not found, please enter a valid program id
        "500":
          description: Internal Server Error
